### ISSUE TITLE
The code of detection part

### ISSUE THREAD

**Issue by Vi-Ocean** [ZhangYuanhan-AI/visual_prompt_retrieval#1]
Hello, I am very interested in this job. But I am a little confused about the implementation of the detection part. When will the detection code be released?

Looking forward to your reply.

**Comment by ZhangYuanhan-AI** [comment]
Hi, thanks for your interest. We plan to release the detection part in the next week.

**Comment by ZhangYuanhan-AI** [comment]
> benboerbababoerben

Hi, the plan for releasing the detection part will be at the end of March.
