### ISSUE TITLE
[Bug] KeyError in  get_top50_images_val

### ISSUE THREAD

**Issue by Chenfeng1271** [ZhangYuanhan-AI/visual_prompt_retrieval#2]
Hi, I met a bug in the running supervised prompt retrieval.
`sh evaluate/srun_seg_evaluate.sh features_vit-laion2b_trn output_vit-laion2b-clip_trn`
![image](https://user-images.githubusercontent.com/24824628/220513094-fb19b6d3-2c32-4191-8c31-46aab90bb131.png)
The step is followed with readme instructions. This bug is raised from loading the Rank50 prompt images calculated by  `python tools/calculate_similariity.py features_vit-laion2b trn trn.` Interestingly, I smoothly run the unsupervised version  and  generated the segmentation results using the same code.  

After comparing these two JSON file of top50-similarity in supervised and unsupervised versions, I notice their keys are different. Did I make mistakes?

**Comment by ZhangYuanhan-AI** [comment]
Fix at https://github.com/ZhangYuanhan-AI/visual_prompt_retrieval/blob/8c307493d4ac8f2b5652345b9004b21703eb9294/evaluate/pascal_dataloader.py#L42
