### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by yuntaodu** [ZhangYuanhan-AI/visual_prompt_retrieval#3]
does the input in line 10 - line 12 of tools/calculate_similariity.py mean sys.argv[1], sys.argv[2], sys.argv[3]?

the current code is: 

eatures_name = sys.argv[1]
source_split = sys.argv[1]
target_split = sys.argv[2]

**Comment by ZhangYuanhan-AI** [comment]
Yes. The input from the terminal.
