### ISSUE TITLE
Failed to download pre-trained model

### ISSUE THREAD

**Issue by mobaigy** [ZhangYuanhan-AI/visual_prompt_retrieval#6]
The SupPR models for each pascal-5i split is uploaded in link.But the last.pth file corresponding to folder2 and folder3 in this link is invalid and gives an error after downloading, is there a problem here?

**Comment by ZhangYuanhan-AI** [comment]
Can you share me with your downloading log?

**Comment by mobaigy** [comment]
https://entuedu-my.sharepoint.com/personal/yuanhan002_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyuanhan002%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fin%2Dcontext%20learning%2Fweights&ga=1

**Comment by ZhangYuanhan-AI** [comment]
> https://entuedu-my.sharepoint.com/personal/yuanhan002_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyuanhan002%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fin%2Dcontext%20learning%2Fweights&ga=1

Hi, it is ok from my side.

**Comment by mobaigy** [comment]
Thank you for your answer, I can now download normally and use it properly, but many times before I tried to download the file after it did not work properly, it may be because of the unstable network. Thanks for your help.
