### ISSUE TITLE
srun_train_pretrain.sh

### ISSUE THREAD

**Issue by mobaigy** [ZhangYuanhan-AI/visual_prompt_retrieval#7]
SupPR.md mentions the command sh srun_train_pretrain.sh, but I can't find the srun_train_pretrain.sh file, is there a specific training file for that?

**Comment by ZhangYuanhan-AI** [comment]
https://github.com/ZhangYuanhan-AI/SupContrast/blob/pre-train-vit-freeze-encoder/srun_train_pretrain.sh 

**Comment by mobaigy** [comment]
Thank you for your answer.

**Comment by ZhangYuanhan-AI** [comment]
> Thank you for your answer.

Please carefully follow the instructions in "SupPR.md" 🤣
