### ISSUE TITLE
Empty iou_dict in get_positive_negative.py

### ISSUE THREAD

**Issue by mobaigy** [ZhangYuanhan-AI/visual_prompt_retrieval#9]
Thanks for your work, I had the same problem：
In the course of debugging get_positive_negative.py, I found that running the：
`    for img_name in iou_dict:
        if img_name in iou_dict[img_name]:
            del iou_dict[img_name][img_name]`
Then iou_dict will become empty，like this：
![image](https://github.com/ZhangYuanhan-AI/visual_prompt_retrieval/assets/92010891/1cc5cc6b-6429-48e6-942e-42a985ebbf92)
So the sorted_iou and the sorted_iou_names is empty.
Are there any steps here that I'm missing?

**Comment by ZhangYuanhan-AI** [comment]
#8

**Comment by mobaigy** [comment]
Thank you!
